#!/bin/bash
# Reddit Quality Scanner - Finds high-quality深度内容 every hour

CACHE_FILE="$HOME/.openclaw/workspace/scripts/.reddit_seen_cache"
PROXY="http://127.0.0.1:7890"
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

SUBREDDITS=("sociology" "philosophy" "technology" "programming" "MachineLearning" "EffectiveAltruism" "DepthHub" "skeptic" "economics" "science")

echo "=== Reddit Scanner: $(date) ===" 

[[ ! -f "$CACHE_FILE" ]] && touch "$CACHE_FILE"

FRESH=0
REPORT_FILE="/tmp/reddit_report_$(date +%H%M).md"

cat > "$REPORT_FILE" << 'HEADER'
# Reddit 高质量内容快报
Generated by ClawBear 🐻
---
HEADER

for sub in "${SUBREDDITS[@]}"; do
    echo -n "Scanning r/$sub... "
    
    # Fetch data with retry
    data=""
    for i in 1 2 3; do
        data=$(curl -x "$PROXY" -s -A "$UA" \
            "https://www.reddit.com/r/$sub/hot/.json?limit=10" \
            --connect-timeout 5 --max-time 10 2>/dev/null)
        [[ -n "$data" ]] && break
        sleep 1
    done
    
    if [[ -z "$data" ]]; then
        echo "[no data]"
        continue
    fi
    
    # Check if valid JSON
    if ! echo "$data" | python3 -c "import json,sys; d=json.load(sys.stdin)" 2>/dev/null; then
        echo "[invalid JSON]"
        continue
    fi
    
    # Process posts
    posts=$(echo "$data" | python3 << PYEOF
import sys, json, os

CACHE_FILE = os.environ.get('CACHE_FILE', '/tmp/reddit_cache')

data = json.load(sys.stdin)

seen = set()
try:
    with open(CACHE_FILE, 'r') as f:
        seen = set(line.strip() for line in f)
except:
    pass

skip = ['rant', 'update', 'meta', 'lpt:', 'tip', 'my ', 'i ', 'wife', 'husband', 
            'girlfriend', 'boyfriend', 'breakup', 'divorce', 'dating']

found = []
for post in data['data']['children']:
    p = post['data']
    pid = p['id']
    title = p['title']
    score = p['ups']
    comments = p['num_comments']
    permalink = p['permalink']
    
    if pid in seen:
        continue
    if 'CMV:' in title or score < 300 or comments < 10:
        continue
    
    tl = title.lower()
    if any(s in tl for s in skip):
        continue
    
    with open(CACHE_FILE, 'a') as f:
        f.write(pid + '\n')
    
    found.append({
        'sub': p['subreddit'],
        'score': score,
        'comments': comments,
        'title': title,
        'url': 'https://reddit.com' + permalink
    })

print(json.dumps(found))
PYEOF
)

    if [[ -n "$posts" && "$posts" != "[]" ]]; then
        count=$(echo "$posts" | python3 -c "import json,sys; print(len(json.load(sys.stdin)))")
        echo "found $count"
        
        echo "$posts" | python3 -c "
import json,sys
posts = json.load(sys.stdin)
for p in posts:
    print(f'  * [{p[\"sub\"]}] {p[\"title\"]} (↑{p[\"score\"]} 💬{p[\"comments\"]})')
    with open('$REPORT_FILE', 'a') as f:
        f.write(f'**[{p[\"sub\"]}] {p[\"title\"]}**\n')
        f.write(f'Score: {p[\"score\"]} | Comments: {p[\"comments\"]}\n')
        f.write(f'Link: {p[\"url\"]}\n\n')
"
        ((FRESH+=count))
    else
        echo "none"
    fi
    
    sleep 0.5
done

echo ""
echo "New quality posts: $FRESH"

if [[ $FRESH -gt 0 ]]; then
    echo ""
    echo "=== Sending to PocketClaw ==="
    clawpilot send "$REPORT_FILE" 2>/dev/null && echo "✓ Sent!"
fi

rm -f "$REPORT_FILE"
echo "=== Done: $(date) ==="
