#!/usr/bin/env python3
# Reddit Quality Scanner V2 - Only finds truly valuable深度内容
# Criteria: self-posts with depth OR highly-upvoted substantive discussions

import os
import sys
import json
import subprocess
import time
from datetime import datetime

CACHE_FILE = os.path.expanduser("~/.openclaw/workspace/scripts/.reddit_seen_cache_v2")
PROXY = "http://127.0.0.1:7890"
UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

# Quality subreddits - ones that tend to have deeper discussions
QUALITY_SUBS = [
    "truereddit",      # Long-form articles
    "sociology",       # Social analysis
    "philosophy",      # Philosophical discussions  
    "DepthHub",        # In-depth posts only
    "skeptic",        # Scientific skepticism
    "askscience",     # Science Q&A
    "EssayDepth",     # Essays
    "lectures",       # Educational content
]

SKIP_SUBS = ["technology", "politics", "worldnews", "news", "sports", "gaming", 
             "music", "movies", "television", "funny", "pics", "aww", "todayilearned"]

SKIP_PATTERNS = ['rant', 'update', 'meta', 'lpt:', 'tip', 'my ', 'i ', 'wife', 'husband', 
                 'girlfriend', 'boyfriend', 'breakup', 'divorce', 'dating', 'advice',
                 'need advice', 'just me?', 'am i wrong', 'aita', 'story', 'confession']

def load_seen():
    seen = set()
    try:
        with open(CACHE_FILE, 'r') as f:
            seen = set(line.strip() for line in f)
    except:
        pass
    return seen

def save_seen(pids):
    with open(CACHE_FILE, 'a') as f:
        for pid in pids:
            f.write(pid + '\n')

def fetch_subreddit(sub):
    cmd = [
        'curl', '-x', PROXY, '-s', '-A', UA,
        f'https://www.reddit.com/r/{sub}/hot/.json?limit=10',
        '--connect-timeout', '5', '--max-time', '10'
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=15)
        return result.stdout
    except:
        return ""

def is_quality_post(post):
    """判断是否是有质量的深度帖子"""
    p = post['data']
    title = p['title'].lower()
    score = p['ups']
    comments = p['num_comments']
    selftext = p.get('selftext', '')
    num_crossposts = p.get('num_crossposts', 0)
    
    # Skip obvious junk
    for skip in SKIP_PATTERNS:
        if skip in title:
            return False
    
    # Self-post with actual content AND substantial discussion
    if selftext and len(selftext) > 300 and comments > 30:
        return True
    
    # Highly-upvoted substantive link posts with lots of discussion
    if score > 2000 and comments > 100 and selftext == '':
        # But only if it's not just a news link
        domain = p.get('domain', '')
        if 'self.' not in domain and 'reddit.com' not in domain:
            # External article - only include if it's likely substantive
            return True
    
    return False

def main():
    print(f"=== Reddit Quality Scanner V2: {datetime.now()} ===")
    
    seen = load_seen()
    fresh_posts = []
    
    for sub in QUALITY_SUBS:
        print(f"Scanning r/{sub}... ", end='', flush=True)
        
        data = fetch_subreddit(sub)
        if not data:
            print("[no data]")
            continue
        
        try:
            json_data = json.loads(data)
        except:
            print("[invalid JSON]")
            continue
        
        new_pids = []
        sub_posts = []
        
        for post in json_data.get('data', {}).get('children', []):
            p = post['data']
            pid = p['id']
            title = p['title']
            score = p['ups']
            comments = p['num_comments']
            permalink = p['permalink']
            selftext = p.get('selftext', '')[:500] if p.get('selftext') else ''
            author = p.get('author', '?')
            
            if pid in seen:
                continue
            
            if not is_quality_post(post):
                continue
            
            new_pids.append(pid)
            sub_posts.append({
                'sub': p['subreddit'],
                'score': score,
                'comments': comments,
                'title': title,
                'selftext': selftext[:300] if selftext else '',
                'author': author,
                'url': 'https://reddit.com' + permalink
            })
        
        if sub_posts:
            print(f"found {len(sub_posts)}")
            fresh_posts.extend(sub_posts)
            save_seen(new_pids)
        else:
            print("none")
        
        time.sleep(0.5)
    
    print(f"\nQuality posts found: {len(fresh_posts)}")
    
    if fresh_posts:
        report = f"""# Reddit 深度内容快报
Generated by ClawBear 🐻 | {datetime.now().strftime('%Y-%m-%d %H:%M')}

Found {len(fresh_posts)} quality posts this round.

---
"""
        for i, p in enumerate(fresh_posts, 1):
            report += f"## {i}. [{p['sub']}] {p['title']}\n"
            report += f"- Score: {p['score']} | Comments: {p['comments']}\n"
            if p['selftext']:
                report += f"- Preview: {p['selftext'][:200]}...\n"
            report += f"- Link: {p['url']}\n\n"
        
        report_file = f"/tmp/reddit_quality_{datetime.now().strftime('%H%M')}.md"
        with open(report_file, 'w') as f:
            f.write(report)
        
        print(f"\nSending to PocketClaw...")
        result = subprocess.run(['clawpilot', 'send', report_file], 
                              capture_output=True, text=True)
        if result.returncode == 0:
            print("✓ Sent!")
        else:
            print(f"✗ Failed: {result.stderr}")
        
        os.unlink(report_file)
    else:
        print("No quality posts found this round.")
    
    print(f"=== Done: {datetime.now()} ===")

if __name__ == "__main__":
    main()
