#!/usr/bin/env python3
# Reddit Quality Scanner - Finds high-quality深度内容 every hour

import os
import sys
import json
import subprocess
import time
from datetime import datetime

CACHE_FILE = os.path.expanduser("~/.openclaw/workspace/scripts/.reddit_seen_cache")
PROXY = "http://127.0.0.1:7890"
UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

SUBREDDITS = [
    "sociology", "philosophy", "technology", "programming", 
    "MachineLearning", "EffectiveAltruism", "DepthHub", "skeptic", "economics", "science"
]

SKIP_PATTERNS = ['rant', 'update', 'meta', 'lpt:', 'tip', 'my ', 'i ', 'wife', 'husband', 
                 'girlfriend', 'boyfriend', 'breakup', 'divorce', 'dating']

def load_seen():
    seen = set()
    try:
        with open(CACHE_FILE, 'r') as f:
            seen = set(line.strip() for line in f)
    except:
        pass
    return seen

def save_seen(pids):
    with open(CACHE_FILE, 'a') as f:
        for pid in pids:
            f.write(pid + '\n')

def fetch_subreddit(sub):
    cmd = [
        'curl', '-x', PROXY, '-s', '-A', UA,
        f'https://www.reddit.com/r/{sub}/hot/.json?limit=10',
        '--connect-timeout', '5', '--max-time', '10'
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=15)
        return result.stdout
    except:
        return ""

def main():
    print(f"=== Reddit Scanner: {datetime.now()} ===")
    
    seen = load_seen()
    fresh_posts = []
    
    for sub in SUBREDDITS:
        print(f"Scanning r/{sub}... ", end='', flush=True)
        
        data = fetch_subreddit(sub)
        if not data:
            print("[no data]")
            continue
        
        try:
            json_data = json.loads(data)
        except:
            print("[invalid JSON]")
            continue
        
        new_pids = []
        sub_posts = []
        
        for post in json_data.get('data', {}).get('children', []):
            p = post['data']
            pid = p['id']
            title = p['title']
            score = p['ups']
            comments = p['num_comments']
            permalink = p['permalink']
            
            if pid in seen:
                continue
            if 'CMV:' in title or score < 300 or comments < 10:
                continue
            
            tl = title.lower()
            if any(s in tl for s in SKIP_PATTERNS):
                continue
            
            new_pids.append(pid)
            sub_posts.append({
                'sub': p['subreddit'],
                'score': score,
                'comments': comments,
                'title': title,
                'url': 'https://reddit.com' + permalink
            })
        
        if sub_posts:
            print(f"found {len(sub_posts)}")
            fresh_posts.extend(sub_posts)
            save_seen(new_pids)
        else:
            print("none")
        
        time.sleep(0.5)
    
    print(f"\nNew quality posts: {len(fresh_posts)}")
    
    if fresh_posts:
        report = f"""# Reddit 高质量内容快报
Generated by ClawBear 🐻 | {datetime.now().strftime('%Y-%m-%d %H:%M')}

---
"""
        for p in fresh_posts:
            report += f"**[{p['sub']}] {p['title']}**\n"
            report += f"Score: {p['score']} | Comments: {p['comments']}\n"
            report += f"Link: {p['url']}\n\n"
        
        report_file = f"/tmp/reddit_report_{datetime.now().strftime('%H%M')}.md"
        with open(report_file, 'w') as f:
            f.write(report)
        
        print(f"\nSending to PocketClaw...")
        result = subprocess.run(['clawpilot', 'send', report_file], 
                              capture_output=True, text=True)
        if result.returncode == 0:
            print("✓ Sent!")
        else:
            print(f"✗ Failed: {result.stderr}")
        
        os.unlink(report_file)
    
    print(f"=== Done: {datetime.now()} ===")

if __name__ == "__main__":
    main()
